### ISSUE TITLE
GPL incompatible with Apache License 2.0

### ISSUE THREAD

**Issue by antoncohen** [Zetten/puppet-hiera-enc#1]
Hiera is licensed under Apache License 2.0 [1]. puppet-hiera-enc is currently licensed under GPL v2 [2]. These licenses are incompatible [3][4]. Please change the license to a compatible license. I recommend MIT or Apache 2.0 if you would like wider adoption, but license choice is up to you.

[1] https://github.com/puppetlabs/hiera/blob/master/LICENSE
[2] https://github.com/Zetten/puppet-hiera-enc/blob/c6c75d625102eb65f75f2879f04fc9f9d2f940d4/LICENSE.md
[3] https://www.gnu.org/philosophy/license-list.html#apache2
[4] http://en.wikipedia.org/wiki/Apache_License#GPL_compatibility

**Comment by Zetten** [comment]
Oops, good catch.

However I would refer to this line in the Apache license which I take to mean that simply importing and calling functions of the hiera module is not creating a derivative work:

> For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of, the Work and Derivative Works thereof.

Regardless, I've swapped to GPLv3 (6fb4e8ebc8e59c57599c6891be4af0ba2769cccb) which is by all accounts Apache-compatible.
